-- CREA BASE DE DATOS

DROP DATABASE IF EXISTS VIVERO_FENIX;
CREATE DATABASE IF NOT EXISTS VIVERO_FENIX;

-- ABRE BASE DE DATOS
USE VIVERO_FENIX;

drop table if exists CALLES;
drop table if exists BARRIOS;
drop table if exists LOCALIDADES;
drop table if exists PROVINCIAS;
drop table if exists TIPOS_PLANTAS;
drop table if exists CONDICIONES_IVA;
drop table if exists FORMAS_PAGO;
drop table if exists PLANTAS;
drop table if exists CLIENTES;
drop table if exists FACTURAS;
drop table if exists DETALLES_FACTURAS;

-- CREACION DE TABLAS
CREATE TABLE IF NOT EXISTS CALLES (
  COD_CALLE Int,
  NOMBRE    Varchar(30),
  CONSTRAINT PK_CALLES PRIMARY KEY (COD_CALLE)
);

CREATE TABLE IF NOT EXISTS BARRIOS (
  COD_BARRIO Int,
  NOMBRE     Varchar(30),
  CONSTRAINT PK_BARRIOS PRIMARY KEY (COD_BARRIO)
);

CREATE TABLE IF NOT EXISTS LOCALIDADES (
  COD_LOCALIDAD Int,
  NOMBRE        Varchar(30),
  CONSTRAINT PK_LOCALIDAD PRIMARY KEY (COD_LOCALIDAD)
);

CREATE TABLE IF NOT EXISTS PROVINCIAS (
  COD_PROVINCIA Int,
  NOMBRE        Varchar(30),
  CONSTRAINT PK_PROVINCIAS PRIMARY KEY (COD_PROVINCIA)
);

CREATE TABLE IF NOT EXISTS TIPOS_PLANTAS (
  COD_TIPO_PLANTA Int,
  NOMBRE          Varchar(30),
  CONSTRAINT PK_TPLANTAS PRIMARY KEY (COD_TIPO_PLANTA)
);

CREATE TABLE IF NOT EXISTS CONDICIONES_IVA (
  COD_CONDICION_IVA Int,
  DESCRIPCION       Varchar(30),
  CONSTRAINT PK_CONDICIVA PRIMARY KEY (COD_CONDICION_IVA)
);

CREATE TABLE IF NOT EXISTS FORMAS_PAGO (
  COD_FORMA_PAGO Int,
  DESCRIPCION    Varchar(30),
  CONSTRAINT PK_FORMAPAGO PRIMARY KEY (COD_FORMA_PAGO)
);

/*
 COMPLETAR ACA CON EL CREATE DE PLANTAS
*/

CREATE TABLE IF NOT EXISTS CLIENTES (
  COD_CLIENTE       int,
  APELLIDO          Varchar(30),
  NOMBRE            Varchar(30),
  COD_CALLE         int,
  ALTURA            Int,
  COD_BARRIO        Int,
  COD_LOCALIDAD     Int,
  COD_PROVINCIA     Int,
  TELEFONO          numeric,
  COD_CONDICION_IVA Int,
  CUIT              numeric,
  DEUDOR            Varchar(1),
  EMAIL             varchar(75),
  CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE),
  CONSTRAINT FK_CLI_CAL FOREIGN KEY (COD_CALLE) REFERENCES CALLES (COD_CALLE),
  CONSTRAINT FK_CLI_BAR FOREIGN KEY (COD_BARRIO) REFERENCES BARRIOS (COD_BARRIO),
  CONSTRAINT FK_CLI_LOC FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDADES (COD_LOCALIDAD),
  CONSTRAINT FK_CLI_PRO FOREIGN KEY (COD_PROVINCIA) REFERENCES PROVINCIAS (COD_PROVINCIA),
  CONSTRAINT FK_CLI_IVA FOREIGN KEY (COD_CONDICION_IVA) REFERENCES CONDICIONES_IVA (COD_CONDICION_IVA)
);

CREATE TABLE IF NOT EXISTS FACTURAS
(
  NRO_FACTURA    Int,
  FECHA          DATE,
  COD_FORMA_PAGO INT,
  COD_CLIENTE    Int,
  CONSTRAINT PK_FACTURAS PRIMARY KEY (NRO_FACTURA),
  CONSTRAINT FK_FAC_CLI FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTES (COD_CLIENTE),
  CONSTRAINT FK_FAC_FORPAG FOREIGN KEY (COD_FORMA_PAGO) REFERENCES FORMAS_PAGO (COD_FORMA_PAGO)
);

CREATE TABLE IF NOT EXISTS DETALLES_FACTURAS
(
  COD_DETALLE Int,
  COD_PLANTA  Int,
  CANTIDAD    Int,
  NRO_FACTURA Int,
  CONSTRAINT PK_DETFACT PRIMARY KEY (COD_DETALLE),
  CONSTRAINT FK_DETFAC_PLA FOREIGN KEY (COD_PLANTA) REFERENCES PLANTAS (COD_PLANTA),
  CONSTRAINT FK_DETFAC_FAC FOREIGN KEY (NRO_FACTURA) REFERENCES FACTURAS (NRO_FACTURA)
);
